# yaml-language-server: $schema=https://taskfile.dev/schema.json
# cspell:ignore taskfile,vcpkg,msbuild,makefiles,deinit

version: '3'

vars:
  PLATFORMS: [Win32, x64]
  ARCHITECTURES: [x86, x64]
  CONFIGURATIONS:
    - Debug
    - Debug.dll
    - Release
    - Release.dll
    - Self-contained
    - Self-contained(debug)

tasks:
  default:
    cmds:
      - task: check-msbuild

  check-msbuild:
    silent: true
    cmds:
      - for: { var: CONFIGURATIONS }
        task: msbuild
        vars: { CONFIG: '{{ .ITEM }}' }

  build:
    cmds:
      - for: ['Debug', 'Release']
        task: msbuild
        vars: { CONFIG: '{{ .ITEM }}' }

  msbuild:
    vars:
      MSBUILD:
        sh: | # shell
          strings=("Preview" "Enterprise" "Professional" "Community")
          for str in "${strings[@]}"
          do
            result="C:/Program Files/Microsoft Visual Studio/2022/${str}/MSBuild/Current/Bin/amd64/MSBuild.exe"
            if [ -e "$result" ]; then
              echo "$result"
              break
            fi
          done
      MSBUILD_CONFIG: '{{ .CONFIG | default "Debug" }}'
      MSBUILD_SOLUTION: '{{ joinPath .TASKFILE_DIR (.SOLUTION | default "AutoHotkeyx.sln") }}'
      MSBUILD_PLATFORM: '{{ .PLATFORM | default "x64" }}'
    cmds:
      - cmd: echo "Building '{{ .MSBUILD_SOLUTION }}' with '{{ .MSBUILD_CONFIG }}' configuration."
      - cmd: >-
          "{{ .MSBUILD }}"
          /m 
          /t:Build 
          /p:Configuration="{{.MSBUILD_CONFIG}}" 
          /p:Platform="{{.MSBUILD_PLATFORM}}" 
          "{{.MSBUILD_SOLUTION}}"
  
  clang:
    cmds:
      - task: cmake-build
        vars: { CMAKE_PRESET: 'x64-windows-clang' }

  cmake-check:
    cmds:
      - task: cmake-build
        vars: { CMAKE_PRESET: 'x64-windows' }

  cmake-build:
    vars:
      CM_BUILD_CMAKE_PRESET: '{{ .CMAKE_PRESET | default "x64-windows" }}'
    cmds:
      - cmd: cmake --preset "{{ .CM_BUILD_CMAKE_PRESET }}"
      - cmd: cmake --build --preset "{{ .CM_BUILD_CMAKE_PRESET }}"
      - cmd: cmake --build --preset "{{ .CM_BUILD_CMAKE_PRESET }}" --target install

  pre-commit:
    cmds:
      - git add --renormalize .
      - git reset --mixed
      - task revert-whitespace

  revert-whitespace:
    cmds:
      - cmd: git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero -
