# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: AutoHotkeyx.sln
  DEFAULT_CONFIG: Release
  DEFAULT_PLATFORM: x64

permissions:
  contents: read

jobs:
  check:
    runs-on: "windows-latest"
    name: "Validate Build"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        working-directory: ${{ github.workspace }}
        run: >-
          msbuild
          /m
          /p:Configuration="${{env.DEFAULT_CONFIG}}"
          /p:Platform="${{env.DEFAULT_PLATFORM}}"
          "${{env.SOLUTION_FILE_PATH}}"

  build:
    needs: check
    name: "⚙️ Build // ${{ matrix.platform }} // ${{ matrix.config }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        platform: [Win32, x64]
        config:
          - Debug
          - Debug.dll
          - Release
          - Release.dll
          - Self-contained
          - Self-contained(debug)
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{ matrix.platform }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: >-
          msbuild
          /m
          /p:Configuration="${{matrix.config}}"
          /p:Platform="${{matrix.platform}}"
          "${{env.SOLUTION_FILE_PATH}}"
