# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: AutoHotkeyx.sln

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
        config: [Release]
        os: [windows]
    runs-on: "${{ matrix.os }}-latest"
    name: "Check // ${{ matrix.config }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{ matrix.platform }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: msbuild /m /p:Configuration="${{matrix.config}}" /p:Platform="${{matrix.platform}}" ${{env.SOLUTION_FILE_PATH}}

  build:
    needs: check
    name: "Build // ${{ matrix.config }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        platform: [Win32, x64]
        architecture: [x86, x64]
        config:
          - Debug
          - Debug.dll
          - Release
          - Release.dll
          - Self-contained
          - Self-contained(debug)
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{ matrix.platform }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: msbuild /m /p:Configuration="${{matrix.config}}" /p:Platform="${{matrix.platform}}" ${{env.SOLUTION_FILE_PATH}}
